#id:
#  generator:
########################### group start ############################
#  provider: property #property、default
#  machineId: 1 #1~1000
######################### group end ###############################
#  epoch: 1420041600000
#  genMethod: 0 #00：嵌入发布模式 01：中心服务器发布模式 02：REST发布模式 03：保留未用
#  type: 0 #0：最大峰值型 1：最小粒度型
#  version: 0 #0：默认值，以免转化为整型再转化回字符串被截断 1：表示扩展或者扩容中
